baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Yes Operator'
theme = 'yesoperator'
enableGitInfo = true

[Params]

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

# See https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
