baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Yes Operator'
theme = 'yesoperator'
enableGitInfo = true

[Params]

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
